version: '3.8'

services:
  app:
    image: fermatd/dashboard:latest    
    ports:
      - "3000:3000"
    env_file:
      - .env                             
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  worker: 
    image: fermatd/dashboard:latest 
    env_file:
      - .env 
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: node /app/dist/worker.js 

volumes:
  postgres_data:
