name: Deploy to Droplet
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fermatd/dashboard
      CONTAINER_NAME: dashboard-container
      REMOTE_PATH: /dashboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            EMAIL_SERVER_HOST=${{ secrets.EMAIL_SERVER_HOST }}
            EMAIL_SERVER_PORT=${{ secrets.EMAIL_SERVER_PORT }}
            EMAIL_SERVER_USER=${{ secrets.EMAIL_SERVER_USER }}
            EMAIL_SERVER_PASSWORD=${{ secrets.EMAIL_SERVER_PASSWORD }}
            EMAIL_FROM=${{ secrets.EMAIL_FROM }}
            UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
            UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
            UPSTASH_REDIS_HOST=${{ secrets.UPSTASH_REDIS_HOST }}
            UPSTASH_REDIS_PORT=${{ secrets.UPSTASH_REDIS_PORT }}
            UPSTASH_REDIS_PASSWORD=${{ secrets.UPSTASH_REDIS_PASSWORD }}
            NEXT_PUBLIC_EXCHANGE_RATE_API_KEY=${{ secrets.NEXT_PUBLIC_EXCHANGE_RATE_API_KEY }}

      - name: SSH to Droplet & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail

            echo "Writing .env file…"
            cat > "${{ env.REMOTE_PATH }}/.env" <<'EOF'
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            EMAIL_SERVER_HOST=${{ secrets.EMAIL_SERVER_HOST }}
            EMAIL_SERVER_PORT=${{ secrets.EMAIL_SERVER_PORT }}
            EMAIL_SERVER_USER=${{ secrets.EMAIL_SERVER_USER }}
            EMAIL_SERVER_PASSWORD=${{ secrets.EMAIL_SERVER_PASSWORD }}
            EMAIL_FROM=${{ secrets.EMAIL_FROM }}
            UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
            UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
            UPSTASH_REDIS_HOST=${{ secrets.UPSTASH_REDIS_HOST }}
            UPSTASH_REDIS_PORT=${{ secrets.UPSTASH_REDIS_PORT }}
            UPSTASH_REDIS_PASSWORD=${{ secrets.UPSTASH_REDIS_PASSWORD }}
            NEXT_PUBLIC_EXCHANGE_RATE_API_KEY=${{ secrets.NEXT_PUBLIC_EXCHANGE_RATE_API_KEY }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            EOF

            echo "Stopping old container (if any)…"
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true

            echo "Pulling new image…"
            docker pull ${{ env.IMAGE_NAME }}:latest

            echo "Starting container with .env…"
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              --env-file "${{ env.REMOTE_PATH }}/.env" \
              -p 3000:3000 \
              ${{ env.IMAGE_NAME }}:latest

              